import type { Metadata, Viewport } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";
import { Providers } from "@/components/Providers";
import { InstallBanner } from "@/components/InstallBanner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL ?? "http://localhost:3000";
const SITE_DESCRIPTION =
  "Pay-per-tap premium content with invisible app-balance payments.";

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  // Per-route layouts set `title: "Search"` etc. and inherit this template,
  // producing unique, descriptive document titles ("Search · Veil").
  title: {
    default: "Veil — lift the veil",
    template: "%s · Veil",
  },
  description: SITE_DESCRIPTION,
  applicationName: "Veil",
  appleWebApp: {
    capable: true,
    statusBarStyle: "black-translucent",
    title: "Veil",
  },
  formatDetection: { telephone: false },
  manifest: "/manifest.webmanifest",
  icons: {
    apple: "/apple-touch-icon.png",
  },
  // og/twitter images are generated by app/opengraph-image.tsx and wired in
  // automatically; these tags give shared links a title + description.
  openGraph: {
    type: "website",
    siteName: "Veil",
    title: "Veil — lift the veil",
    description: SITE_DESCRIPTION,
    url: SITE_URL,
  },
  twitter: {
    card: "summary_large_image",
    title: "Veil — lift the veil",
    description: SITE_DESCRIPTION,
  },
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover", // handles iPhone notch
  themeColor: "#121012",
};

// Applies the persisted theme before paint (dark default → no class). No FOUC.
const themeScript = `(function(){try{if(localStorage.getItem('veil-theme')==='light'){document.documentElement.classList.add('light')}}catch(e){}})();`;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="bg-bg text-text flex min-h-full flex-col">
        <ClerkProvider>
          <Script
            id="veil-theme"
            strategy="beforeInteractive"
            dangerouslySetInnerHTML={{ __html: themeScript }}
          />
          <Providers>
            {children}
            <InstallBanner />
          </Providers>
        </ClerkProvider>
      </body>
    </html>
  );
}
